### ISSUE TITLE
config file trouble

### ISSUE THREAD

**Issue by Niemi** [AGWA/titus#1]
# Hmm, maybe i can't see somethng special, but output is here ....

niemi@ndeb7:~/STUDex# titus --config /home/niemi/STUDex/titus.conf
titus: Configuration error: Unable to read TLS key file: /etc/ssl/private/localhost.key : No such file or directory
niemi@ndeb7:~/STUDex# ls -l /etc/ssl/private/
total 8
-rw-r--r-- 1 root root     2484 Jan  6 14:06 localhost.key

**Comment by AGWA** [comment]
Looks like you have a trailing space character in your config file that's being interpreted as part of the filename:

```
/etc/ssl/private/localhost.key : No such file or directory
                              ^
```

You should probably check other lines for trailing space characters too, lest they cause other problems.  I'll fix titus so that it ignores trailing spaces.

**Comment by AGWA** [comment]
Trailing whitespace ignored as of c3380a445e03b17c6d855d0263d45628fdb16071. Thanks for bringing this to my attention.
