### ISSUE TITLE
Is this abandonware?

### ISSUE THREAD

**Issue by feld** [AGWA/titus#6]
No updates in years, clearly it has never been tested on platforms with OpenSSL 1.1.0+ as it requires at least 07a65ecfaaafcb0f22d321e1f524a3a33ec42d14 which came out after the 0.3 tag.

**Comment by AGWA** [comment]
Hey @feld, alas the answer is yes.  With mature memory-safe TLS stacks like Go's crypto/tls and Rust's rustls, I don't have a need for titus anymore.  I just pushed some minor fixes that I had lying around, and tagged 0.4, which includes 07a65ecfaaafcb0f22d321e1f524a3a33ec42d14 and works with OpenSSL 1.1.0+.  In all likelihood this will be the final release, and I will be archiving the GitHub repo in the near future.

**Comment by feld** [comment]
That's perfectly OK. Just wanted to know where this was at and if I should keep packaging it in FreeBSD. I'll get 0.4 pushed and then mark it as deprecated to be removed in 6 months.

**Comment by AGWA** [comment]
Sounds good. Thanks for maintaining the FreeBSD package all these years!
